### ISSUE TITLE
MAA: Modelling Ambiguous Assignments for Multi-Person Tracking in Crowds 代码链接失效

### ISSUE THREAD

**Issue by yinyankun** [luanshiyinyang/awesome-multiple-object-tracking#18]
请问 MAA: Modelling Ambiguous Assignments for Multi-Person Tracking in Crowds这篇论文代码链接已经失效，还有新的链接地址吗？

**Comment by luanshiyinyang** [comment]
The code is not yet public for this paper, we have updated the link error in the repository.
