### ISSUE TITLE
MeMOT code url is wrong

### ISSUE THREAD

**Issue by Curry-Christopher** [luanshiyinyang/awesome-multiple-object-tracking#20]
hi, thanks the summary about MOT. The code url of MeMOT may be wrong

**Comment by HELLORPG** [comment]
I think they do not make their code public. So the author of this repo makes this URL point to this repo itself, as many webs do the same. But maybe deleting this `code` part of MeMOT is even better.

**Comment by HELLORPG** [comment]
We removed this repo link in our current commit.
