### ISSUE TITLE
Hope to update this resource  continuely

### ISSUE THREAD

**Issue by qingchunlizhi** [luanshiyinyang/awesome-multiple-object-tracking#21]
Thank you for your great work，will you update this resource  continuely?

**Comment by HELLORPG** [comment]
Same question. Looks like he is been away from this repo for a long time. The frequency of GitHub code submissions has also dropped a lot.

**Comment by luanshiyinyang** [comment]
Our team members will continue to update this repository, and we also invite like-minded researchers to join in the maintenance of this repository.
