### ISSUE TITLE
问题请教：多目标跟踪的理解

### ISSUE THREAD

**Issue by MunLee001** [luanshiyinyang/awesome-multiple-object-tracking#27]
您好！
请问这里的多目标跟踪好像涉及到视觉，和一般这种雷达，红外传感器多目标跟踪的有什么区别吗？
我看您这里的评价指标也和我之前看的有所不同，之前经常看到OSPA这种评价指标。

期待您的回复！
祝您生活愉快！

**Comment by HELLORPG** [comment]
我个人的理解是，因为一开始的时候，当 MOT 这个任务提出的时候，是在视觉模态（普通视频）上的，因此，当大家提到 MOT 的时候，默认的基准是视觉模态。后续的发展例如 3D Point MOT，包括您说的雷达/红外传感都是在后续发展中出现的新模态，因此没有收录在这个 (Default MOT) 仓库中。类比于当提到单目标跟踪，目标检测的时候，大家想到的基准也是在常规视觉上进行处理的方法。
例如：
[https://github.com/amusi/awesome-object-detection](https://github.com/amusi/awesome-object-detection) 应该也是主要收录了常规的视觉目标检测（COCO Dataset 之类），而 [https://github.com/BigTeacher-777/Awesome-Monocular-3D-detection](https://github.com/BigTeacher-777/Awesome-Monocular-3D-detection) 中则收录了单目 3D 目标检测的各类文章。

**Comment by MunLee001** [comment]
感谢您的解答！

**Comment by HELLORPG** [comment]
> 感谢您的解答！

不客气～
也祝您生活愉快。
